# Generated by Django 3.2.8 on 2021-10-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('categoria', models.CharField(max_length=255)),
                ('preco', models.CharField(max_length=255)),
                ('quantidade', models.CharField(max_length=255)),
            ],
        ),
    ]
